- name: Setup homebrew install path.
  file:
    path: "{{ homebrew_install_path }}"
    group: admin
    mode: 0775
    state: directory
  become: yes

- name: Ensure proper permissions on /usr/local dirs.
  file:
    path: "{{ item }}"
    group: admin
    mode: 0775
  with_items:
    - "/usr/local"
    - "/usr/local/bin"
  become: yes

- name: Check if homebrew binary is already in place.
  stat: path=/usr/local/bin/brew
  register: homebrew_binary

- name: Ensure homebrew is installed.
  git:
    repo: https://github.com/Homebrew/homebrew.git
    version: master
    dest: "{{ homebrew_install_path }}"
    update: yes
    accept_hostkey: yes
  when: homebrew_binary.stat.exists == false

- name: Symlink brew to /usr/local/bin/brew.
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: /usr/local/bin/brew
    state: link
  when: homebrew_binary.stat.exists == false
  become: yes

# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Install brew-cask.
  homebrew: "name=caskroom/cask/brew-cask state=present"
