---
- name: Remove default background db.
  file: name="~/Library/Application Support/Dock/desktoppicture.db" state=absent

- name: Remove default background.
  sudo: yes
  file: name="/System/Library/CoreServices/DefaultDesktop.jpg" state=absent

- name: Install background.
  sudo: yes
  copy: src=DefaultDesktop.jpg dest="/System/Library/CoreServices" mode=0755

- name: Set OS X defaults.
  script: osx-defaults.sh "{{ hostname }}"
