---
- name: Allow brew installed zsh.
  sudo: yes
  lineinfile: dest=/etc/shells line="/usr/local/bin/zsh"

- name: Set shell.
  sudo: yes
  shell: 'chsh -s /usr/local/bin/zsh {{ ansible_env["USER"] }}'
