---
- name: clone vundle git repo
  git: repo=https://github.com/gmarik/Vundle.vim.git dest="~/.vim/bundle/Vundle.vim"

- name: Set OS X defaults.
  script: osx-defaults.sh "{{ hostname }}"

- name: Install vim plugins
  command: vim +PluginInstall +qall

- name: Install iterm2 plist
  copy: src=com.googlecode.iterm2.plist dest="~/Library/Preferences/com.googlecode.iterm2.plist" mode=0600

- name: Load iterm2 plist
  shell: defaults read com.googlecode.iterm2
