
# CIS 2.1.1
- name: Disable Bluetooth
  command: defaults write /Library/Preferences/com.apple.Bluetooth \ ControllerPowerState -int 0

- name: Kill Bluetooth
  sudo: yes
  command: killall -HUP blued

# CIS 2.1.3
- name: Display Bluetooth icon
  command: defaults write com.apple.systemuiserver menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"

# CIS 2.2.1
- name: Set NTP
  sudo: yes
  command: systemsetup -setnetworktimeserver pool.ntp.org

- name: Enable NTP
  sudo: yes
  command: systemsetup -setnetworktimeserver on

# CIS 2.4.1
- name: Disable Apple Events
  sudo: yes
  command: systemsetup -setremoteappleevents off

# CIS 2.4.5
- name: Disable Remote Login (SSH)
  sudo: yes
  command: systemsetup -setremotelogin off

# CIS 2.4.8
- name: Disable AFP
  sudo: yes
  command: launchctl unload -w /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist

- name: Disable SMB
  sudo: yes
  command: launchctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist

# CIS 2.5.1
- name: Disable wake on lan
  sudo: yes
  command: pmset -a womp 0

# CIS 2.6.2
- name: Enable Gatekeeper
  sudo: yes
  command: sudo spctl --master-enable

# CIS 2.6.3
- name: Enable Firewall
  sudo: yes
  command: defaults write /Library/Preferences/com.apple.alf globalstate - int 2

# CIS 2.6.4
- name: Enable Stealth Mode
  sudo: yes
  command: /usr/libexec/ApplicationFirewall/socketfilterfw `--setstealthmode on`

# CIS 2.7.3
- name: Disable iCloud Drive
  command: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
