---
- name: Set defaults.
  hosts: all
  gather_facts: yes

  vars_prompt:
    - name: "host"
      prompt: "Hostname"
      default: "apple"

  roles:
    - { role: osx-defaults, hostname: "{{ host }}" }
