---
- name: Configure OSX Environment.
  hosts: all
  gather_facts: yes

  vars_prompt:
    - name: "hostname"
      prompt: "Hostname"
      default: "null"

  roles:
    - osx-homebrew
    - { role: osx-customize, hostname: "{{ hostname }}" }
